### PR TITLE
Add headers to editor sections

### PR DESCRIPTION
**Pull request by JakubKohoutek**
When I started working with the editor (I opened the blank one), it was very confusing for me that there are four different sections (windows) where you can type code. It wasn't very clear to me which section is dedicated to what kind of code or if there is any difference between them whatsoever.
I think that adding headers to those sections can improve the user experience. WDYT?

### CODE REVIEW

**Comment by MatthiasSaihttam** [comment]
I like the idea. I don’t love the current layout (with the default margin on an `h3` they take up a lot of space on the page).  If you get a chance, could you add a class name to them, and maybe a rule in `program.css`. If not that’s fine, I can merge tomorrow and then play around with layout myself.

**Comment by JakubKohoutek** [comment]
> If you get a chance, could you add a class name to them, and maybe a rule in program.css.

I will try to improve the styling 👍

**Comment by JakubKohoutek** [comment]
@MatthiasSaihttam - I made the styling improvements, check it out. I hope you like it 👍

**Comment by MatthiasSaihttam** [comment]
That looks much better! I might play around with the styling more in the future, but I'll go ahead and merge now. Thanks for your contribution!

**Pull request merged**
