### PR TITLE
Sort comment replies chronologically

### PR DESCRIPTION
**Pull request by cdrani**

### CODE REVIEW

**Comment by MatthiasSaihttam** [comment]
Can you also add that to the line 5 lines up (140, it should look similar)? There are two different database queries depending on the specificity of the API call.

**Comment by cdrani** [comment]
Oh, yeah. Will do.

**Comment by MatthiasSaihttam** [comment]
I was unable to reproduce the original issue, #64, locally. (I'm guessing this a difference in the default sorts of mysql (used on the server) and sqlite (used locally).) But nothing crashes when I ran it locally, so I'm going to merge and update the site, and see if this works.

**Comment by MatthiasSaihttam** [comment]
Hey, it worked! Thanks for the help, @cdrani.

**Pull request merged**
