### PR TITLE
Use innerHTML instead of document.write

### PR DESCRIPTION
**Pull request by JakubKohoutek**
document.body.innerHTML used instead of document.write as requested in issue #99. I couldn't find any other occurrences of `document.write` (only in JQuery and html2canvas packages which I consider external dependencies that shouldn't be modified)

### CODE REVIEW

**Comment by MatthiasSaihttam** [comment]
Thanks for checking out the repository. You've got the right one place that the issue was referring to. But I tried out your code and it doesn't work, I think because the incoming code string needs to be the entire document, not just the body's HTML. I threw together an example [here](https://ourjseditor.com/program/oRtijY), partially because I couldn't resist the opportunity to get a little meta. I haven't looked into other solutions yet though, I don't know if it's even possible with `.innerHTML`. I'd love to have you look into it more though.

**Comment by JakubKohoutek** [comment]
> Thanks for checking out the repository. You've got the right one place that the issue was referring to. But I tried out your code and it doesn't work, I think because the incoming code string needs to be the entire document, not just the body's HTML. I threw together an example [here](https://ourjseditor.com/program/oRtijY), partially because I couldn't resist the opportunity to get a little meta. I haven't looked into other solutions yet though, I don't know if it's even possible with `.innerHTML`. I'd love to have you look into it more though.

Hi Matthias, I am sorry that it didn't work, I tried it in separation in chrome developer tools, but I haven't been able to debug it inside a real app. I will investigate the issue further.
Two minor notes/questions:
- In the readme, there is a suggestion to run `npm run build-watch`, but this script is not inside package.json => is there a reason for it? Should I remove it from the readme or try to make the watch mode work?
- I tried to run the editor locally, but there is an iframe URL hardcoded (https://exec.ourjseditor.com) and I can't see my local changes there. Can I change the configuration so that I can try if my solution works inside a real app?

Thank you.

**Comment by JakubKohoutek** [comment]
OK, so I improved the code to work in all browsers, you can try it [here](https://ourjseditor.com/program/J5yNG-).
I've tried it in successfully on:
* Chrome on Mac
* Safari on Mac
* Firefox on Mac
* Chrome on Windows 10
* Edge on Windows 10

**Comment by MatthiasSaihttam** [comment]
Okay, good to be aware of cross browser issues (I'm using Firefox, so that's why I wasn't seeing anything).

> In the readme, there is a suggestion to run npm run build-watch

Thanks for reminding me that it didn't exist; the README got a little ahead of package.json. I just added the command. It's optional though, it is just supposed to re-run build when React code changes, but you should be able to just run `npm run build` once.

> Can I change the configuration so that I can try if my solution works inside a real app?

Normally what I do to test `exec` frame code locally is start a new server in the `exec` directory, on a different port. So in a new terminal window in that directory, `python3 -m http.server 8080`. And then I manually change the url for the execution frame to be `http://localhost:8080`.

As for the code itself, can you change `.body.innerHTML` to `.getElementsByTagName("html")[0].innerHTML`, so that we're overwriting more of the HTML for the page, not just the body.

**Comment by JakubKohoutek** [comment]
After further investigation I found out that the `document.write()` is the only solution that works always reliably. InnerHTML works only when I open the  exec index.html page separately and `postMessage()` to the page, but once it is in iframe inside OurJSEditor application, it doesn't work.
I tried many variations, but the code I pushed now is the only one that works reliably - it's only advantage over what's in `master` is that it's just a little cleaner - I leave it up to you if you want to include this change to your repo or not.
> Normally what I do to test exec frame code locally is start a new server in the exec directory, on a different port. So in a new terminal window in that directory, python3 -m http.server 8080. And then I manually change the url for the execution frame to be http://localhost:8080.

I did that and it helped me a lot with debugging, thank you for the tip 🌈

**Pull request closed without merging**
